//
//  CARItem.m
//  Cargo
//
//  Created by Julien Gil on 24/01/2017.
//  Copyright © 2017 55 SAS. All rights reserved.
//

#import "CargoItem.h"

@implementation CargoItem

/**
 Creates a CargoItem, which will be changed into an Item object for a specific SDK
 The revenue is automatically calculated with (quantity * unit price)
 
 @param itemName Name of the item
 @param unitPrice unit price for the item
 @param quantity number of items
 @return the CARItem object
 */
- (id)initWithName:(NSString *)itemName andUnitPrice:(float)unitPrice andQuantity:(unsigned int)quantity {
    if (self = [super init]) {
        self.name = itemName;
        self.unitPrice = unitPrice;
        self.quantity = quantity;
        self.revenue = unitPrice * quantity;
    }
    return self;
}

/**
 Creates a CargoItem, which will be changed into an Item object for a specific SDK

 @param itemName Name of the item
 @param unitPrice unit price for the item
 @param quantity number of items
 @param revenue revenue generated by this group of items
 @return the CARItem object
 */
- (id)initWithName:(NSString *)itemName
      andUnitPrice:(float)unitPrice
       andQuantity:(UInt32)quantity
        andRevenue:(float)revenue {
    if (self = [super init]) {
        self.name = itemName;
        self.unitPrice = unitPrice;
        self.quantity = quantity;
        self.revenue = revenue;
    }
    return self;
}


/**
 Returns a String describing the object

 @return a NSString describing the object with its attributes.
 */
- (NSString *)description {
    NSMutableString* s = [NSMutableString stringWithFormat:@"{CargoItem: \"name\": \"%@\", \"unitPrice\": \"%f\", \"quantity\": \"%u\",\"revenue\": \"%f\"", self.name, self.unitPrice, self.quantity, self.revenue];
    if ((self.attribute1) != nil) {
        NSString* temp = [NSString stringWithFormat:@",\"attribute1\": \"%@\"", self.attribute1];
        s = [NSMutableString stringWithFormat:@"%@%@", s, temp];
    }
    if ((self.attribute2) != nil) {
        NSString* temp = [NSString stringWithFormat:@",\"attribute2\": \"%@\"", self.attribute2];
        s = [NSMutableString stringWithFormat:@"%@%@", s, temp];
    }
    if ((self.attribute3) != nil) {
        NSString* temp = [NSString stringWithFormat:@",\"attribute3\": \"%@\"", self.attribute3];
        s = [NSMutableString stringWithFormat:@"%@%@", s, temp];
    }
    if ((self.attribute4) != nil) {
        NSString* temp = [NSString stringWithFormat:@",\"attribute4\": \"%@\"", self.attribute4];
        s = [NSMutableString stringWithFormat:@"%@%@", s, temp];
    }
    if ((self.attribute5) != nil) {
        NSString* temp = [NSString stringWithFormat:@",\"attribute5\": \"%@\"", self.attribute5];
        s = [NSMutableString stringWithFormat:@"%@%@", s, temp];
    }
    s = [NSMutableString stringWithFormat:@"%@%@", s, @"}"];
    return s;
}

@end
