language: objective-c
osx_image: xcode8
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo

before_install: - gem install cocoapods --pre
before_install: - pod repo update --silent
before_install: - brew update
before_install: - brew install xctool

script:
  - xctool -workspace Cargo.xcworkspace -scheme Cargo build test -sdk iphonesimulator

notifications:
  slack: cargo55:oT6MdyRm7WZzNe51cLdbsVo7
