language: objective-c
osx_image: xcode8
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo

before_install: 
  - gem install cocoapods --pre
  - pod repo update --silent

script:
  - travis_retry xcodebuild test -workspace Cargo.xcworkspace -scheme Cargo -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty

notifications:
  slack: cargo55:oT6MdyRm7WZzNe51cLdbsVo7
