language: objective-c
osx_image: xcode8
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo
xcode_sdk: iphonesimulator9.3

before_install: gem install cocoapods --pre
before_install: pod repo update

script:
  - xcodebuild -workspace Cargo.xcworkspace -scheme Cargo -sdk iphonesimulator build test

notifications:
  slack: cargo55:oT6MdyRm7WZzNe51cLdbsVo7
