language: objective-c
osx_image: xcode8.2
xcode_scheme: Cargo

script:
  - xctool -workspace Cargo.xcworkspace -scheme Cargo build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 5e20da68-d862-4214-a079-43a5659b41a0