language: objective-c
osx_image: xcode8
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo

script:
  - xcodebuild test 'ONLY_ACTIVE_ARCH=NO' 'ARCHS=arm64 armv7 armv7s i386 x86_64' -workspace Cargo.xcworkspace -scheme Cargo -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
