language: objective-c
osx_image: xcode8.2
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo

before_install:
  - pod update

script:
  - xctool -workspace Cargo.xcworkspace -scheme CargoTest build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)