coverage:
  range: 50...95
  round: nearest
  precision: 0

ignore:
  - "App/**/*"  # ignore the app folders and all its contents
  - "AppTests/**/*"  # ignore the app folders and all its contents
  - "AppUITests/**/*"  # ignore the app folders and all its contents
  - "CargoTest/**/*"  # ignore the CargoTest folders and all its contents